name: revinvest
services:
    webapp:
        image: revinvest_webapp:latest
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                WAR_FILE: ${WAR_FILE_PATH}
        container_name: revinvest_webapp
        environment:
            LOG_LEVEL: WARN # TRACE | DEBUG | INFO | WARN | ERROR | FATAL
            DB_URL: ${DB_CONTAINER_PATH}
        ports:
            - "${APP_PORT}:8080"
        volumes:
            - "./${DB_HOST_PATH}:${DB_CONTAINER_PATH}"
