name: revinvest_dev
services:
    webapp:
        environment:
            JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        ports:
            - "${DEBUG_PORT}:5005"
        volumes:
            - ./conf/dev_context.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml
            - ./target/classes:/usr/local/tomcat/dev_classes
